# Generated by Django 3.0.2 on 2020-03-01 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this page. Generated by the system.', max_length=600)),
                ('details', models.TextField(default='', help_text='Write the details of your page here.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this page was created. Automatically generated when the model saves.')),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this page was updated. Automatically generated when the model updates.')),
                ('contact_person', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('coordinator', models.ForeignKey(blank=True, default='', help_text='The user that posted this article.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
